apiVersion: apps/v1
kind: Deployment
metadata:
  name: rangoli-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rangoli
  template:
    metadata:
      labels:
        app: rangoli
    spec:
      containers:
        - name: rangoli
          image: rangoli-app:v3
          ports:
            - containerPort: 80
